name: Notificação de Pull Request Mergeado

on:
  pull_request:
    types:
      - closed # O evento será disparado quando um PR for fechado (merge ou rejeitado)

jobs:
  notify:
    if: github.event.pull_request.merged == true # Garante que só executa se o PR foi mergeado
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificação para o Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          # Obter informações do pull request
          REPO_URL="https://github.com/${{ github.repository }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_TITLE="${{ github.event.pull_request.title }}"

          # Enviar mensagem formatada
          curl -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
            -d chat_id=${TELEGRAM_CHAT_ID} \
            -d parse_mode=Markdown \
            -d text="
✨ *Pull Request Mergeado!*

*Repositório:* [${{ github.repository }}](${REPO_URL})

*Autor:* ${PR_AUTHOR}

*Título:* [${PR_TITLE}](${PR_URL})
"
